### ISSUE TITLE
can't run train and decode stages on aishell dataset

### ISSUE THREAD

**Issue by MNCTTY** [kaituoxu/ListenAttendSpell#8]
Hello! I tried to run run.sh for aishell dataset to test the usage of your code/algo and I didn't meet success in this task. I faced a problem on a stage 3: 

```
Stage 3: Network Training
run.pl: job failed, log is in exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/train.log
Stage 4: Decoding
run.pl: job failed, log is in exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/decode_test_beam30_nbest1_ml100/decode.log
2019-08-23 20:05:08,030 (json2trn:24) INFO: reading exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/decode_test_beam30_nbest1_ml100/data.json
Traceback (most recent call last):
  File "/home/karina/Listen-Attend-Spell/egs/aishell/../../src/utils/json2trn.py", line 25, in <module>
    with open(args.json, 'r') as f:
IOError: [Errno 2] No such file or directory: 'exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/decode_test_beam30_nbest1_ml100/data.json'
cp: cannot stat 'exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/decode_test_beam30_nbest1_ml100/ref.trn': No such file or directory
cp: cannot stat 'exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/decode_test_beam30_nbest1_ml100/hyp.trn': No such file or directory
Traceback (most recent call last):
  File "/home/karina/Listen-Attend-Spell/egs/aishell/../../src/utils/filt.py", line 21, in <module>
    with open(args.infile) as textfile:
IOError: [Errno 2] No such file or directory: 'exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/decode_test_beam30_nbest1_ml100/ref.trn.org'
Traceback (most recent call last):
  File "/home/karina/Listen-Attend-Spell/egs/aishell/../../src/utils/filt.py", line 21, in <module>
    with open(args.infile) as textfile:
IOError: [Errno 2] No such file or directory: 'exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/decode_test_beam30_nbest1_ml100/hyp.trn.org'
write a CER (or TER) result in exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/decode_test_beam30_nbest1_ml100/result.txt
|      SPKR        |         # Snt                   # Wrd         |      Corr              Sub              Del              Ins              Err            S.Err      |
|      Sum/Avg     |             0                       0         |       0.0              0.0              0.0              0.0              0.0              0.0      |

```

what should I do to fix it?

**Comment by kaituoxu** [comment]
> Stage 3: Network Training
run.pl: job failed, log is in exp/train_in240_hidden256_e3_lstm_drop0.2_dot_emb512_hidden512_d1_epoch20_norm5_bs32_mli800_mlo150_adam_lr1e-3_mmt0_l21e-5_delta/train.log

See log.

**Comment by MNCTTY** [comment]
There is very strange error in log:

```
Training...
Traceback (most recent call last):
  File "/home/karina/Listen-Attend-Spell/egs/aishell/../../src/bin/train.py", line 146, in <module>
    main(args)
  File "/home/karina/Listen-Attend-Spell/egs/aishell/../../src/bin/train.py", line 140, in main
    solver.train()
  File "/home/karina/Listen-Attend-Spell/src/solver/solver.py", line 70, in train
    tr_avg_loss = self._run_one_epoch(epoch)
  File "/home/karina/Listen-Attend-Spell/src/solver/solver.py", line 164, in _run_one_epoch
    loss = self.model(padded_input, input_lengths, padded_target)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/karina/Listen-Attend-Spell/src/models/seq2seq.py", line 24, in forward
    encoder_padded_outputs, _ = self.encoder(padded_input, input_lengths)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/karina/Listen-Attend-Spell/src/models/encoder.py", line 39, in forward
    packed_output, hidden = self.rnn(packed_input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 182, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
TypeError: lstm() received an invalid combination of arguments - got (Tensor, Tensor, tuple, list, bool, int, float, bool, int), but expected one of:
 * (Tensor data, Tensor batch_sizes, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, !tuple!, !list!, bool, int, float, bool, !int!)
 * (Tensor input, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
      didn't match because some of the arguments have invalid types: (Tensor, !Tensor!, !tuple!, !list!, !bool!, int, !float!, bool, !int!)
```

It seems like there is a problem in a torch files or in the original code. I do everything in according to your readme on aishell original data.

Do you have some ideas?

**Comment by kaituoxu** [comment]
Modify https://github.com/kaituoxu/Listen-Attend-Spell/blob/master/src/models/encoder.py#L22 to
`bidirectional=bool(bidirectional))`

**Comment by MNCTTY** [comment]
done. but not better now

```
Training...
Traceback (most recent call last):
  File "/home/karina/Listen-Attend-Spell/egs/aishell/../../src/bin/train.py", line 146, in <module>
    main(args)
  File "/home/karina/Listen-Attend-Spell/egs/aishell/../../src/bin/train.py", line 140, in main
    solver.train()
  File "/home/karina/Listen-Attend-Spell/src/solver/solver.py", line 70, in train
    tr_avg_loss = self._run_one_epoch(epoch)
  File "/home/karina/Listen-Attend-Spell/src/solver/solver.py", line 164, in _run_one_epoch
    loss = self.model(padded_input, input_lengths, padded_target)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/karina/Listen-Attend-Spell/src/models/seq2seq.py", line 24, in forward
    encoder_padded_outputs, _ = self.encoder(padded_input, input_lengths)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/karina/Listen-Attend-Spell/src/models/encoder.py", line 39, in forward
    packed_output, hidden = self.rnn(packed_input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 182, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
TypeError: lstm() received an invalid combination of arguments - got (Tensor, Tensor, tuple, list, bool, int, float, bool, int), but expected one of:
 * (Tensor data, Tensor batch_sizes, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, !tuple!, !list!, bool, int, float, bool, !int!)
 * (Tensor input, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
      didn't match because some of the arguments have invalid types: (Tensor, !Tensor!, !tuple!, !list!, !bool!, int, !float!, bool, !int!)
```

**Comment by MNCTTY** [comment]
still didn't find a solution
do you have any ideas where the problem can be?

**Comment by MNCTTY** [comment]
thanks
